# Generated by Django 3.1.5 on 2021-01-22 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='shippingCost',
            new_name='shipping_cost',
        ),
    ]
